Lexicon_LMS/Models/Course.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Lexicon_LMS.Models
{
    public class Course
    {

        public int Id { get; set; }

        [Required]
        [StringLength(100)]
        public string Name { get; set; }

        [Required]
        [StringLength(1200)]
        public string Description { get; set; }

        public virtual ICollection<ApplicationUser> Users { get; set; }

        [Required]
        [Display(Name = "Start date")]
        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:yyyy-MM-dd}")]
        public DateTime StartDate { get; set; }

        [Required]
        [Display(Name = "End date")]
        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:yyyy-MM-dd}")]
        public DateTime EndDate { get; set; }


        public virtual ICollection<Module> Modules { get; set; }

        public virtual ICollection<Event> Events { get; set; }

        public virtual ICollection<Document> Documents { get; set; }
    }   
        
 }

Lexicon_LMS/Models/Module.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Lexicon_LMS.Models
{
    public class Module
    {
        public int Id { get; set; }

        [Required]
        [StringLength(100)]
        public string Name { get; set; }

        [Required]
        [StringLength(1200)]
        public string Description { get; set; }

        [Required]
        [Display(Name = "Start date")]
        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:yyyy-MM-dd}")]
        public DateTime StartDate { get; set; }

        [Required]
        [Display(Name = "End date")]
        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:yyyy-MM-dd}")]
        public DateTime EndDate { get; set; }

        [Required]
        [Display(Name = "Course")]
        public int CourseId { get; set; }
        [ForeignKey("CourseId")]
        public virtual Course Course { get; set; }

        public virtual ICollection<Activity> Activity { get; set; }
        public virtual ICollection<Document> Documents { get; set; }
    }
}

Lexicon_LMS/Controllers/Api/HomeController.cs
using Lexicon_LMS.Models;
using System.Net;
using System.Web.Http;

namespace Lexicon_LMS.Controllers.Api
{
    public class HomeController : ApiController
    {
        private ApplicationDbContext db;

        public HomeController()
        {
            db = new ApplicationDbContext();
        }

        [HttpDelete]
        [Authorize(Roles = Role.Teacher)]
        public IHttpActionResult DeleteModule(int? id)
        {
            if (id == null)
                return StatusCode(HttpStatusCode.BadRequest);

            Module module = db.Modules.Find(id);

            if (module == null)
                return StatusCode(HttpStatusCode.NotFound);

            db.Modules.Remove(module);
            db.SaveChanges();

            return Ok();
        }


    }
}

Lexicon_LMS/Controllers/BasicSchedulerController.cs
using DHTMLX.Common;
using DHTMLX.Scheduler;
using DHTMLX.Scheduler.Data;
using Lexicon_LMS.Models;
using Lexicon_LMS.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;



namespace Lexicon_LMS.Controllers
{
    public class BasicSchedulerController : Controller
    {

        private ApplicationDbContext db;


        public CourseID LatestCourseID = new CourseID();


        public BasicSchedulerController()
        {

            db = new ApplicationDbContext();

        }

  
        // GET: BasicScheduler
        public ActionResult Index(int? id)
        {
            var course = db.Courses.FirstOrDefault(c => c.Id == id);


            var sched = new DHXScheduler(this);
            sched.Skin = DHXScheduler.Skins.Terrace;
            sched.LoadData = true;
            sched.EnableDataprocessor = true;
            sched.InitialDate = course.StartDate;


            var ViewModel = new CourseDhxViewModel()
            {
                Course = course,
                DHX = sched
            };


            var nrOfCourseIds = db.CurrentCourseID.Count();


            if (nrOfCourseIds > 0)
            {
                var CourseIdList = db.CurrentCourseID.Where(c => c.Compare == 1).ToList();

                foreach (var courseId in CourseIdList)
                {
                    db.CurrentCourseID.Remove(courseId);
                    db.SaveChanges();
                }
            }


            LatestCourseID.InputID(course.Id);

            db.CurrentCourseID.Add(LatestCourseID);

            db.SaveChanges();



            return View(ViewModel);
        }



        public ContentResult Data()
        {

            var courseId = db.CurrentCourseID.FirstOrDefault(c => c.Compare == 1);
            var currentCourseID = courseId.CurrentCourse_ID;
            db.SaveChanges();


            return (new SchedulerAjaxData(
                new SchedulerContext().Courses.Single(e => e.Id == currentCourseID).Events
                .Select(e => new { e.id, e.text, e.start_date, e.end_date})
                )
                );
        }



        [Authorize(Roles = Role.Teacher)]
        public ContentResult Save(int? id, FormCollection actionValues)
        {
            var db = new ApplicationDbContext();

            var action = new DataAction(actionValues);
            var changedEvent = DHXEventsHelper.Bind<Event>(actionValues);
            var entities = new SchedulerContext();

            var eventz = entities.Events.Count();


            try
            {
                switch (action.Type)
                {
                    case DataActionTypes.Insert:

                        entities.Events.Add(changedEvent);

                        entities.SaveChanges();

                        var coreId_ = db.CurrentCourseID.FirstOrDefault(c => c.Compare == 1);
                        var insertCurrentCourseID = coreId_.CurrentCourse_ID;

                        var _target = entities.Events.Single(e => e.id == changedEvent.id);

                        _target.Eventz(changedEvent.text, changedEvent.start_date, changedEvent.end_date, insertCurrentCourseID);


                        break;


                    case DataActionTypes.Delete:

                        changedEvent = entities.Events.FirstOrDefault(ev => ev.id == action.SourceId);
                        entities.Events.Remove(changedEvent);

                        break;


                    default:// "update"

                        var courseId_ = db.CurrentCourseID.FirstOrDefault(c => c.Compare == 1);
                        var updateCurrentCourseID = courseId_.CurrentCourse_ID;

                        var target = entities.Events.Single(e => e.id == changedEvent.id);

                        target.Eventz(changedEvent.text, changedEvent.start_date, changedEvent.end_date, updateCurrentCourseID);


                        DHXEventsHelper.Update(target, changedEvent, new List<string> { "id" });
                        break;
                }


                entities.SaveChanges();
                action.TargetId = changedEvent.id;

            }
            catch (Exception a)
            {
                action.Type = DataActionTypes.Error;
            }


            return (new AjaxSaveResponse(action));


        } 
    }  
}      

Lexicon_LMS/Controllers/DocumentController.cs
using Lexicon_LMS.Models;
using Microsoft.AspNet.Identity;
using System;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace Lexicon_LMS.Controllers
{
    public class DocumentController : Controller
    {

        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: list student hand-ins for a specified activity, including those students who have not yet submitted a document
        [Authorize(Roles = Role.Teacher)]
        public ActionResult ListStudentDocuments(int? activityId)
        {
            var courseId = db.Activities.Find(activityId).Module.CourseId;
            var documents = db.Documents.Where(x => x.ActivityId == activityId);
            var studentDocuments = db.Users
                .Where(x => x.CourseId == courseId)
                .Select(x => new StudentDocumentViewModel
                { UserId = x.Id, FirstName = x.FirstName, LastName = x.LastName, Document = documents.FirstOrDefault(d => d.Author.Id == x.Id) })
                .OrderBy(x => x.Document == null)
                .ThenBy(x => x.LastName)
                .ThenBy(x => x.FirstName);

            var activity = db.Activities.Find(activityId);
            ViewBag.Title = $"Student assignments ( {activity.Module.Course.Name} - {activity.Module.Name} - {activity.Name} )";
            ViewBag.ReturnUrl = Url.Action("Course", "Home", new { id = activity.Module.Course.Id, ModuleId = TempData["ModuleId"] });
            return View(studentDocuments.ToList());
        }

        [Authorize]
        public ActionResult AddFileToSystem(int? courseId, int? moduleId, int? activityId, bool? isPartial)
        {
            var document = new Document
            {
                CourseId = courseId,
                ModuleId = moduleId,
                ActivityId = activityId,
            };

            TempData.Keep("ReturnUrl");
            if (isPartial ?? false)
                return PartialView(document);
            else
                return View(document);
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddFileToSystem(HttpPostedFileBase file, [Bind(Include = "Description,CourseId,ModuleId,ActivityId")]  Document document)
        {
            ModelState.Remove("FileName");

            document.FileName = Path.GetFileName(file.FileName);
            document.CreateTime = DateTime.Now;
            var foo = ModelState;
            if (ModelState.IsValid)
            {
                var userId = User.Identity.GetUserId();
                // Validate user rights:
                if (User.IsInRole(Role.Student))
                {
                    // Activity must allow studend assignments and student must be enrolled in course
                    var courseId = db.Activities.Find(document.ActivityId).Module.Course.Id;
                    if (db.Users.Find(userId).CourseId != courseId)
                    {
                        return new HttpStatusCodeResult(HttpStatusCode.BadRequest, "Student not allowed to upload in this course (student not enrolled in specified course");
                    }
                    document.StudentDocument = new StudentDocument { Graded = false };
                }
                document.Author = db.Users.Find(userId);

                db.Documents.Add(document);
                db.SaveChanges();

                // Write file to disc
                var rootPath = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "App_Data", "Docs");
                var fileName = Path.GetFileName(file.FileName);
                var fullPath = Path.Combine(rootPath, document.Id.ToString(), fileName);
                Directory.CreateDirectory(Path.GetDirectoryName(fullPath));
                file.SaveAs(fullPath);

                if (TempData["ReturnUrl"] != null)
                    return Redirect(TempData["ReturnUrl"].ToString());
                else
                    return RedirectToAction("Index", "Home");
            }
            TempData.Keep("ReturnUrl");
            return View(document);
        }

        [Authorize]
        [HttpGet]
        public FileResult GetFile(int id)
        {
            var document = db.Documents.Find(id);
            var rootPath = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "App_Data", "Docs");
            var fileName = document.FileName;
            var fullPath = Path.Combine(rootPath, document.Id.ToString(), fileName);

            return File(fullPath, "application/octet-stream", document.FileName);
        }
    }
}

Lexicon_LMS/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Lexicon_LMS/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Lexicon_LMS/Views/Home/Course.cshtml
@using Lexicon_LMS.Models
@using Microsoft.AspNet.Identity

@model Lexicon_LMS.Models.Course

@{
    ViewBag.Title = "Course";

    
}

<div class="user-course">

<h2 style="color:darkred;"><b>@Model.Name</b></h2>
<div>
    
     @* @Html.ActionLink("Schedule", "Index" ,"BasicScheduler", routeValues: new { id = Model.Id }, htmlAttributes: new { @class = "btn btn-default btn-sm" }) *@

</div>

    @Html.ActionLink("Schedule", "Index", "BasicScheduler", routeValues: new { id = Model.Id }, htmlAttributes: new { @class = "btn btn-default btn-sm" })

    @if (User.IsInRole(Role.Teacher))
    {
        @Html.ActionLink("Edit Course", "EditCourse", "Home", routeValues: new { role = Role.Teacher, id = Model.Id }, htmlAttributes: new { @class = "btn btn-default btn-sm" })
        <a href="#" class="js-delete-entity btn btn-default btn-sm" title="Delete" data-user-api="/HomeApi/DeleteCourse/" data-user-id="@Model.Id" data-user-remove=".user-course" data-user-message="Delete course @Html.DisplayFor(m => m.Name)">Delete course</a>
        @Ajax.ActionLink("Add document", "AddFileToSystem", "Document", new { courseId = Model.Id, ispartial = true }, new AjaxOptions
   {
       UpdateTargetId = "UpdateContentDiv", // <-- DOM element ID to update
       InsertionMode = InsertionMode.Replace, // <-- Replace the content of DOM element
       HttpMethod = "GET", // <-- HTTP method


   },
                                                            new { @class = "btn btn-default btn-sm" } //-- Class
                                                        )

    }
    <a href="#" class="btn btn-default btn-sm" data-toggle="collapse" data-target=".Description">Course info</a>


    <hr />
    <div class="col-sm-12">
        <div id="UpdateContentDiv1">


        </div>
        <div class="Description collapse in">
            @*<h4>@Html.DisplayFor(model => model.Name)</h4>*@

            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.Name)
                </dt>

                <dd style="color:darkred;">
                    <b>@Html.DisplayFor(model => model.Name)</b>
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Description)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Description)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.StartDate)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.StartDate)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.EndDate)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.EndDate)
                </dd>

                @*@if (Model.Documents.Count > 0)
                    {
                        <dt>
                            Documents
                        </dt>
                    }*@

                <dt>
                    Documents
                </dt>

                <dd>
                    @foreach (var file in Model.Documents)
            {
                        <span class="space">
                            <a href="@Url.Action("GetFile", "Document", new { id = file.Id })" download="@file.FileName"
                               title="created @file.CreateTime.ToString() by @file.Author.FullName">@file.FileName</a>
                        </span>
                    }
                </dd>

                @*<h4>Documents: </h4>
                    <div class="row">
                        @foreach (var file in Model.Documents)
                    {
                            <div class="col-sm-3">
                                <a href="@Url.Action("GetFile","Document", new { moduleId = file.Id })" download="@file.FileName"><span class="glyphicon glyphicon-file"></span>@file.FileName</a>
                            </div>
                        }
                    </div>*@





            </dl>

            <hr />

        </div>
    </div>



    <div class="col-sm-3">
        <div class="row">
            <h3 style="color:darkred;"><b>Course modules</b></h3>

            @if (User.IsInRole(Role.Teacher))
            {
                @Html.ActionLink("Add new module", "CreateModule", "Home", routeValues: new { courseId = Model.Id, returnUrl = Request.RawUrl }, htmlAttributes: new { @class = "btn btn-default btn-sm" })
                <hr />
            }

            @foreach (var module in Model.Modules.OrderBy(x => x.StartDate))
            {
                <div class="user-module">
                    <p>
                        @Ajax.ActionLink(module.Name, "ListActivity", "Home", new { id = module.Id }, new AjaxOptions { UpdateTargetId = "UpdateContentDiv", InsertionMode = InsertionMode.Replace, HttpMethod = "GET" }, new { @class = "btn btn-link module-link" })

                        @if (User.IsInRole(Role.Teacher))
                {
                            <span class="pull-right">
                                @Ajax.ActionLink(" ", "EditModule", "Home", new { id = module.Id }, new AjaxOptions { UpdateTargetId = "UpdateContentDiv", InsertionMode = InsertionMode.Replace, HttpMethod = "GET" }, new { @class = "glyphicon glyphicon-edit btn-gly1", title = "Edit" })
                                |
                                <a href="#" class="js-delete-entity glyphicon glyphicon-trash btn-gly1" title="Delete" data-user-api="/HomeApi/DeleteModule/" data-user-id="@module.Id" data-user-removeAjax="#UpdateContentDiv" data-user-remove=".user-module" data-user-message="Delete module @Html.DisplayFor(m => module.Name)"></a>
                            </span>
                        }

                    </p>
                    <p><i> @Html.DisplayFor(m => module.StartDate) &ndash; @Html.DisplayFor(m => module.EndDate)</i></p>
                    <p><b>@module.Description</b></p>
                </div>
            }
            @if (!Model.Modules.Any())
            {
                <p>No modules registered</p>
            }

        </div>
    </div>
    <div class="col-sm-9">

        <div id="UpdateContentDiv">
            @*Render module data here*@
            @if (ViewBag.ModuleId != null)
            {
                Html.RenderAction("ListActivity", routeValues: new { id = ViewBag.ModuleId });
            }
        </div>
    </div>

    <hr />

    <div class="col-sm-12">
        <div class="row">
            <hr />
            <strong><a href="#" class="btn btn-link headling-users" data-toggle="collapse" data-target=".users">Course student</a></strong><br />
            @if (User.IsInRole(Role.Teacher))
            {
                @Html.ActionLink("Add new student", "Register", "Account", routeValues: new { role = Role.Student, courseid = Model.Id }, htmlAttributes: new { @class = "btn btn-default btn-sm btn-side" })
            }
            <div class="users collapse in">
                @foreach (var student in Model.Users.ToList())
                {
                    <div class="col-sm-4 col-md-4">
                        <p><strong>@student.FullName</strong> <a href="mailto:@student.Email">@student.Email</a></p>
                    </div>
                }
            </div>
        </div>
    </div>
</div>

Lexicon_LMS/Views/Home/CreateActivity.cshtml
@model Lexicon_LMS.Models.Activity

@{
    ViewBag.Title = "CreateActivity";
}

<h2>CreateActivity</h2>

@using (Html.BeginForm(routeValues: new { returnUrl = ViewBag.ReturnUrl })) 
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(m => m.ModuleId)

        <hr />
        @Html.ValidationSummary(true, "", new { @class = "alert alert-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.Name)
            @Html.TextBoxFor(model => model.Name, new { @class = "form-control", autofocus = "true" } )
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description)
            @Html.TextBoxFor(model => model.Description, new { @class = "form-control" } )
            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StartDate)
            <div class="input-group datetimepicker" id="datetimepicker">
                @Html.EditorFor(model => model.StartDate, new { htmlAttributes = new { type = "text", @class = "form-control datetimepicker", @Value = "", placeholder = "enter start date" } })
                <span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span>
            </div>
             @Html.ValidationMessageFor(model => model.StartDate, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EndDate)
            <div class="input-group datetimepicker" id="datetimepicker">
                @Html.EditorFor(model => model.EndDate, new { htmlAttributes = new { type = "text", @class = "form-control datetimepicker", @Value = "", placeholder = "enter end date" } })
                <span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span>
            </div>
            @Html.ValidationMessageFor(model => model.EndDate, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ActivityTypeId)
            @Html.DropDownList("ActivityTypeId", new SelectList(Model.ActivityTypes, "Id", "Name"),"", new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.ActivityTypeId, "", new { @class = "text-danger" })
         </div>

        <div class="form-group">
             <input type="submit" value="Create" class="btn btn-default" />
            <a href="@TempData["ReturnUrl"]" class="btn btn-default">Cancel</a>
        </div>
}

Lexicon_LMS/Views/Home/EditCourse.cshtml
@model Lexicon_LMS.Models.Course
@{
    ViewBag.Title = "Edit course";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<h2>@ViewBag.Title</h2>


@using (Html.BeginForm("SaveCourse", "Home", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(m => m.Id)
    <hr />
    @Html.ValidationSummary("", new { @class = "text-danger" })

    <div class="form-group">
        @Html.LabelFor(m => m.Name)
        @Html.TextBoxFor(m => m.Name, new { @class = "form-control", placeholder = "enter course name" })
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.Description)
        @Html.TextAreaFor(m => m.Description, new { @class = "form-control", placeholder = "enter course description" })
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.StartDate)
        <div class="input-group" id="datetimepicker">
            @Html.EditorFor(m => m.StartDate, new { htmlAttributes = new { type = "text", @class = "form-control datepickerDate", placeholder = "enter start date" } })
            <span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span>
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.EndDate)
        <div class="input-group" id="datetimepicker">
            @Html.EditorFor(m => m.EndDate, new { htmlAttributes = new { type = "text", @class = "form-control datepickerDate", placeholder = "enter end date" } })
            <span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span>

        </div>
    </div>
    <div class="form-group">
        <input type="submit" class="btn btn-default" value="Save"  />
        <a href="@TempData["ReturnUrl"]" class="btn btn-default">Cancel</a>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Lexicon_LMS/Views/Home/Index.cshtml
@model System.Web.Mvc.HandleErrorInfo

@{
    ViewBag.Title = "Index";
}


<h2>@ViewBag.Title</h2>

<p>This page is empty, probably because you have no course registred</p>

Lexicon_LMS/Views/Home/ListActivity.cshtml
@using Lexicon_LMS.Models
@using Microsoft.AspNet.Identity

@model Lexicon_LMS.Models.Module


<h3>Module: @Model.Name</h3>
<div class="activity-table">
    @if (User.IsInRole(Role.Teacher))
    {
        @Html.ActionLink("Add new activity", "CreateActivity", "Home", new { id = Model.Id }, htmlAttributes: new { @class = "btn btn-default btn-sm newActivityBtn" })
        @Html.ActionLink("Add document", "AddFileToSystem", "Document", new { moduleId = Model.Id, }, htmlAttributes: new { @class = "btn btn-default btn-sm newActivityBtn2" })
    }

    <table class="table table-responsive dl-horizontal table-striped table-bordered">
        <tr>

            <th>
                Name
            </th>
            <th>
                Description
            </th>
            <th>
                Time
            </th>
            @*<th>
                    End Date
                </th>*@
            <th>
                Activity type
            </th>

            <th>
                @if (User.IsInRole(Role.Student))
                {
                    <p>Documents</p>
                }
            </th>

        </tr>

@foreach (var item in Model.Activity.OrderBy(x => x.StartDate)) {
  
    <tr class="user-tr">
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            <p>
            @Html.DisplayFor(modelItem => item.Description)
            @if (User.IsInRole(Role.Teacher))
            {
                <span class="right">@Html.ActionLink(" ", "AddFileToSystem", "Document", routeValues: new { activityId = item.Id }, htmlAttributes: new { @class = "glyphicon glyphicon-paperclip", title = "Add documents" })</span>
            }
            </p>
            <p>
            @foreach (var file in item.Documents.Where(x => x.StudentDocumentId == null))
            {
                <span class="space"><a href="@Url.Action("GetFile","Document", new { id = file.Id })" download="@file.FileName" title="created @file.CreateTime.ToString() by @file.Author.FullName">@file.FileName</a></span>
            }
            </p>

        </td>
        <td>
            @Html.DisplayFor(modelItem => item.StartDate) -
            @Html.DisplayFor(modelItem => item.EndDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ActivityType.Name)
            @if (User.IsInRole(Role.Teacher) && item.ActivityType.AllowStudentDocuments)
            {
                <span class="right">
                    @Html.ActionLink(" ", "ListStudentDocuments", "Document", routeValues: new { activityId = item.Id }, htmlAttributes: new { @class = "glyphicon glyphicon-list-alt btn-gly", title = "view assignments" })
                </span>
            }
        </td>
        @if (User.IsInRole(Role.Student))
        {
        <td>
            @if (item.ActivityType.AllowStudentDocuments && User.IsInRole(Role.Student))
            {
                var document = item.Documents.FirstOrDefault(x => x.Author.Id == User.Identity.GetUserId());
                if (document == null)
                {
                <p>@Html.ActionLink("upload assignment", "AddFileToSystem", "Document", routeValues: new { activityId = item.Id }, htmlAttributes: new { @class = "btn btn-default btn-xs" })</p>
                }
                else
                {
                    <p>submitted: <a href="@Url.Action("GetFile", "Document", new { id = document.Id })" download="@document.FileName"><span class="glyphicon glyphicon-file"></span>@document.FileName</a></p>
                }

                        }
                    </td>
                }


                @if (User.IsInRole(Role.Teacher))
                {
                    <td>

        @Ajax.ActionLink(" ", "EditActivity", "Home", new { id = item.Id }, new AjaxOptions
   {
       UpdateTargetId = "UpdateContentDiv",
       InsertionMode = InsertionMode.Replace,
       HttpMethod = "GET",
   },
                                    new
                                    {
                                        @class = "glyphicon glyphicon-edit btn-gly",
                                        title = "Edit"
                                    })|
        <a href="#" class="js-delete-entity glyphicon glyphicon-trash btn-gly-trash-act" title="Delete" data-user-api="/HomeApi/DeleteActivity/" data-user-id="@item.Id" data-user-remove=".user-tr" data-user-message="Delete activity @Html.DisplayFor(modelItem => item.Name)"></a>
    </td>
}

            </tr>
        }

    </table>

    <span>Module documents: </span>
    @foreach (var file in Model.Documents)
    {
        <span class="space">
            <a href="@Url.Action("GetFile", "Document", new { id = file.Id })" download="@file.FileName" title="created @file.CreateTime.ToString() by @file.Author.FullName">@file.FileName</a>
        </span>
    }



</div>